/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/runs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Runs */
    get: operations['list_runs_api_v1_runs_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/test-reports': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create Test Report */
    post: operations['create_test_report_api_v1_test_reports_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** RunListItem */
    RunListItem: {
      /**
       * Run Id
       * Format: uuid
       */
      run_id: string
      /** Runner Id */
      runner_id: string
      /** Runner Owner */
      runner_owner: string
      /**
       * Started At
       * Format: date-time
       */
      started_at: string
      /**
       * Ended At
       * Format: date-time
       */
      ended_at: string
      /** Duration Ms */
      duration_ms: number | null
      /**
       * Status
       * @enum {string}
       */
      status: 'passed' | 'failed' | 'error'
      /** Total Count */
      total_count: number
      /** Failed Count */
      failed_count: number
      /** Pass Rate */
      pass_rate: number | null
      /** Report Url */
      report_url: string | null
    }
    /** RunListResponse */
    RunListResponse: {
      /** Items */
      items: components['schemas']['RunListItem'][]
      /** Page */
      page: number
      /** Page Size */
      page_size: number
      /** Total */
      total: number
      /** Total Pages */
      total_pages: number
    }
    /** TestReportCase */
    TestReportCase: {
      /** Case Id */
      case_id: string
      /** Case Name */
      case_name: string
      /** Module */
      module?: string | null
      /**
       * Result
       * @enum {string}
       */
      result: 'passed' | 'failed' | 'skipped' | 'blocked' | 'error'
      /** Duration Ms */
      duration_ms?: number | null
      /** Error Type */
      error_type?: string | null
      /** Error Message */
      error_message?: string | null
      /** Log Url */
      log_url?: string | null
      /** Screenshot Url */
      screenshot_url?: string | null
    }
    /** TestReportRequest */
    TestReportRequest: {
      /** Idempotency Key */
      idempotency_key: string
      runner: components['schemas']['TestReportRunner']
      run: components['schemas']['TestReportRun']
      summary: components['schemas']['TestReportSummary']
      /** Cases */
      cases: components['schemas']['TestReportCase'][]
    }
    /** TestReportResponse */
    TestReportResponse: {
      /**
       * Run Id
       * Format: uuid
       */
      run_id: string
      /**
       * Status
       * @enum {string}
       */
      status: 'imported' | 'duplicate'
      /** Message */
      message: string
    }
    /** TestReportRun */
    TestReportRun: {
      /**
       * Started At
       * Format: date-time
       */
      started_at: string
      /**
       * Ended At
       * Format: date-time
       */
      ended_at: string
      /** Duration Ms */
      duration_ms?: number | null
      /**
       * Status
       * @enum {string}
       */
      status: 'passed' | 'failed' | 'error'
      /** Report Url */
      report_url?: string | null
    }
    /** TestReportRunner */
    TestReportRunner: {
      /** Runner Id */
      runner_id: string
      /** Runner Name */
      runner_name?: string | null
      /** Runner Owner */
      runner_owner: string
      /** Ip */
      ip?: string | null
    }
    /** TestReportSummary */
    TestReportSummary: {
      /** Total Count */
      total_count: number
      /** Passed Count */
      passed_count: number
      /** Failed Count */
      failed_count: number
      /** Skipped Count */
      skipped_count: number
      /** Blocked Count */
      blocked_count: number
      /** Error Count */
      error_count: number
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_runs_api_v1_runs_get: {
    parameters: {
      query?: {
        started_at_from?: string | null
        started_at_to?: string | null
        runner_owner?: string | null
        runner_id?: string | null
        status?: ('passed' | 'failed' | 'error') | null
        page?: number
        page_size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RunListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_test_report_api_v1_test_reports_post: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TestReportRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TestReportResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
}
