/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/case-reports': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Case Reports */
    get: operations['list_case_reports_api_v1_case_reports_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/case-reports/{case_report_id}/report': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Case Report File */
    get: operations['get_case_report_file_api_v1_case_reports__case_report_id__report_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/test-reports': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create Test Report */
    post: operations['create_test_report_api_v1_test_reports_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** Body_create_test_report_api_v1_test_reports_post */
    Body_create_test_report_api_v1_test_reports_post: {
      /** Payload */
      payload: string
      /** Report File */
      report_file: string
    }
    /** CaseReportListItem */
    CaseReportListItem: {
      /**
       * Case Report Id
       * Format: uuid
       */
      case_report_id: string
      /** Runner Id */
      runner_id: string
      /** Runner Owner */
      runner_owner: string
      /** Case Id */
      case_id: string
      /** Case Name */
      case_name: string
      /** Module */
      module: string | null
      /**
       * Started At
       * Format: date-time
       */
      started_at: string
      /**
       * Ended At
       * Format: date-time
       */
      ended_at: string
      /** Duration Ms */
      duration_ms: number | null
      /**
       * Result
       * @enum {string}
       */
      result: 'passed' | 'failed' | 'skipped' | 'blocked' | 'error'
      /** Report Url */
      report_url: string
      /** Error Type */
      error_type: string | null
      /** Error Message */
      error_message: string | null
    }
    /** CaseReportListResponse */
    CaseReportListResponse: {
      /** Items */
      items: components['schemas']['CaseReportListItem'][]
      /** Page */
      page: number
      /** Page Size */
      page_size: number
      /** Total */
      total: number
      /** Total Pages */
      total_pages: number
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** TestReportResponse */
    TestReportResponse: {
      /**
       * Case Report Id
       * Format: uuid
       */
      case_report_id: string
      /** Report Url */
      report_url: string
      /**
       * Status
       * @enum {string}
       */
      status: 'imported' | 'duplicate'
      /** Message */
      message: string
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_case_reports_api_v1_case_reports_get: {
    parameters: {
      query?: {
        started_at_from?: string | null
        started_at_to?: string | null
        runner_owner?: string | null
        runner_id?: string | null
        result?: ('passed' | 'failed' | 'skipped' | 'blocked' | 'error') | null
        module?: string | null
        query?: string | null
        page?: number
        page_size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CaseReportListResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_case_report_file_api_v1_case_reports__case_report_id__report_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        case_report_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_test_report_api_v1_test_reports_post: {
    parameters: {
      query?: never
      header?: {
        authorization?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_create_test_report_api_v1_test_reports_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TestReportResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
}
